//
// Created by joelh on 19/10/2023.
//

#ifndef MRMP_IMPLEMENTATION_CONSTANTS_H
#define MRMP_IMPLEMENTATION_CONSTANTS_H

const double RADIUS = 100;
const int MAX_POLY_SIZE = 100;

const int OBSTACLE_OFFSET = 5;
const int ROBOT_SIZE = 4;

const int NMBR_START_POS = 10;
const int WORKSPACE_COMPLEXITY = 50;

const int MONOCHROMATIC_SEPARATION = 4;
const int BICHROMATIC_SEPARATION = 4;


#endif//MRMP_IMPLEMENTATION_CONSTANTS_H
