//
// Created by joelh on 13/11/2023.
//

#ifndef MRMP_IMPLEMENTATION_CHRMOTIONGRAPHSOLVER_H
#define MRMP_IMPLEMENTATION_CHRMOTIONGRAPHSOLVER_H


class ChrMotionGraphSolver
{
};


#endif//MRMP_IMPLEMENTATION_CHRMOTIONGRAPHSOLVER_H
