//
// Created by joelh on 13/11/2023.
//

#ifndef MRMP_IMPLEMENTATION_CHRRESIDUALCOMPONENTGRAPHGENERATOR_H
#define MRMP_IMPLEMENTATION_CHRRESIDUALCOMPONENTGRAPHGENERATOR_H


class ChrResidualComponentGraphGenerator
{
};


#endif//MRMP_IMPLEMENTATION_CHRRESIDUALCOMPONENTGRAPHGENERATOR_H
